all: homeworkFT homeworkFFT

homeworkFT: homeworkFT.c
	gcc -o homeworkFT homeworkFT.c -O3 -lpthread -lm -Wall

homeworkFFT: homeworkFFT.c
	gcc -o homeworkFFT homeworkFFT.c -O3 -lpthread -lm -Wall

clean:
	rm homeworkFFT homeworkFT